FROM python:3.12.4-slim

RUN pip install --upgrade pip

COPY ./hello_library /hello_library
RUN pip install -e /hello_library

WORKDIR /tests

CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]